// Code generated by MockGen. DO NOT EDIT.
// Source: ./docker/cleanup_client.go
//
// Generated by this command:
//
//	mockgen -package mocks -source=./docker/cleanup_client.go -destination=./docker/cleanup/mocks/mock_cleanup_client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dockertypes "github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/build"
	container "github.com/docker/docker/api/types/container"
	image "github.com/docker/docker/api/types/image"

	gomock "go.uber.org/mock/gomock"
)

// MockCleanupClient is a mock of CleanupClient interface.
type MockCleanupClient struct {
	ctrl     *gomock.Controller
	recorder *MockCleanupClientMockRecorder
	isgomock struct{}
}

// MockCleanupClientMockRecorder is the mock recorder for MockCleanupClient.
type MockCleanupClientMockRecorder struct {
	mock *MockCleanupClient
}

// NewMockCleanupClient creates a new mock instance.
func NewMockCleanupClient(ctrl *gomock.Controller) *MockCleanupClient {
	mock := &MockCleanupClient{ctrl: ctrl}
	mock.recorder = &MockCleanupClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCleanupClient) EXPECT() *MockCleanupClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCleanupClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCleanupClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCleanupClient)(nil).Close))
}

// ContainerList mocks base method.
func (m *MockCleanupClient) ContainerList(ctx context.Context, opts container.ListOptions) ([]container.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerList", ctx, opts)
	ret0, _ := ret[0].([]container.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerList indicates an expected call of ContainerList.
func (mr *MockCleanupClientMockRecorder) ContainerList(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerList", reflect.TypeOf((*MockCleanupClient)(nil).ContainerList), ctx, opts)
}

// ImageList mocks base method.
func (m *MockCleanupClient) ImageList(ctx context.Context, opts image.ListOptions) ([]image.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageList", ctx, opts)
	ret0, _ := ret[0].([]image.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImageList indicates an expected call of ImageList.
func (mr *MockCleanupClientMockRecorder) ImageList(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageList", reflect.TypeOf((*MockCleanupClient)(nil).ImageList), ctx, opts)
}

// ImageRemove mocks base method.
func (m *MockCleanupClient) ImageRemove(ctx context.Context, imageID string, opts image.RemoveOptions) ([]image.DeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageRemove", ctx, imageID, opts)
	ret0, _ := ret[0].([]image.DeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImageRemove indicates an expected call of ImageRemove.
func (mr *MockCleanupClientMockRecorder) ImageRemove(ctx, imageID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageRemove", reflect.TypeOf((*MockCleanupClient)(nil).ImageRemove), ctx, imageID, opts)
}

// DiskUsage mocks base method.
func (m *MockCleanupClient) DiskUsage(ctx context.Context, opts dockertypes.DiskUsageOptions) (dockertypes.DiskUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiskUsage", ctx, opts)
	ret0, _ := ret[0].(dockertypes.DiskUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiskUsage indicates an expected call of DiskUsage.
func (mr *MockCleanupClientMockRecorder) DiskUsage(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiskUsage", reflect.TypeOf((*MockCleanupClient)(nil).DiskUsage), ctx, opts)
}

// BuildCachePrune mocks base method.
func (m *MockCleanupClient) BuildCachePrune(ctx context.Context, opts build.CachePruneOptions) (*build.CachePruneReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildCachePrune", ctx, opts)
	ret0, _ := ret[0].(*build.CachePruneReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildCachePrune indicates an expected call of BuildCachePrune.
func (mr *MockCleanupClientMockRecorder) BuildCachePrune(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildCachePrune", reflect.TypeOf((*MockCleanupClient)(nil).BuildCachePrune), ctx, opts)
}
